complete current version of chk

diff --git a/bin/chk b/bin/chk
--- a/bin/chk
+++ b/bin/chk
@@ -14,50 +14,79 @@
 set -eu -o pipefail
 
 # global variables specification
-_FILE_NAME='job.out'
-_GREP_FLAG=false
-_OUTPUT_FORMAT="%s\t  %s\n"
+FILENAME='job.out'
+FLAG=
+REFORMAT_OUTPUT=true
+OUTPUT_FORMAT="%s\t  %s\n"
+COLUMN=0
+HIDE_PATH=false
 
 function usage() {
   printf '%s\n' \
     "Usage: chk [options]" \
-    'Show the last line of all files in current directory and' \
-    'The last line is displayed if the file name matches.' \
+    'Show the last line of files in current directory and all subdirectories' \
+    'if the file name matches FILENAME.' \
     '' \
     "Options:" \
+    '    -c COLUMN' \
+    '        display only the given COLUMN' \
+    '        note: this is achieved by awk so many tricks can be played.' \
+    '        e.g. chk -c "1, \$3" will display both 1st and 3rd columns.'\
+    '' \
     '    -f FILENAME' \
     '        FILENAME to check, default is "job.out"' \
     '' \
     '    -g FLAG' \
-    '        grep lines with FLAG instead of last line' \
+    '        grep last FLAG instead of show last line' \
+    '' \
+    '    -n' \
+    '        do not reformat the output string' \
+    '' \
+    '    -s' \
+    '        hide the path' \
     ''
 }
 
 function err() {
-  printf "${FUNCNAME[1]} > ERROR MSG > $@" >&2
+  printf "[${FUNCNAME[1]}] -> ERROR: $@" >&2
 }
 
 function format_output() {
-  local __length=-1
-  local __array=("$@")
-  for x in "${__array[@]}"; do
-    [ "${#x}" -gt $__length ] && __length="${#x}"
+  local len_path=-1
+  local array=("$@")
+  for x in "${array[@]}"; do
+    [ "${#x}" -gt $len_path ] && len_path="${#x}"
   done
-  _OUTPUT_FORMAT="\033[34m%-${__length}s\033[0m -> %s\n"
+  local len_msg=$(expr $(tput cols) - $len_path - 2)
+  OUTPUT_FORMAT="\033[34m%-${len_path}s\033[0m  %-${len_msg}.${len_msg}s\n"
 }
 
 function chk() {
-  local __target_files=($(find . -name "$_FILE_NAME"))
-  format_output "${__target_files[@]}"
-  for x in "${__target_files[@]}"; do
-    printf "$_OUTPUT_FORMAT" "$(ls $x)" "$(tail -1 $x)"
+  local target_files=($(find . -name "$FILENAME"))
+  [ ${#target_files[@]} -eq 0 ] && {
+    err "No such files in the directory: $FILENAME \n"
+    exit 1
+  }
+  "$REFORMAT_OUTPUT" && format_output "${target_files[@]}"
+  for x in "${target_files[@]}"; do
+    if [ -z "$FLAG" ]; then
+      info=$(tail -1 $x| awk "{print  $ $COLUMN}") 
+    else
+      info=$(grep "$FLAG" $x | tail -1 | awk "{print $ $COLUMN}")
+    fi
+    $HIDE_PATH && printf "$info\n" || {
+      printf "$OUTPUT_FORMAT" "$(ls $x)" "$info"
+    }
   done
 }
 
-while getopts "f:g:" opt; do
+while getopts "c:f:g:ns" opt; do
   case "$opt" in
-    f) _FILE_NAME="$OPTARG";;
-    g) _GREP_FLAG="$OPTARG";;
+    c) COLUMN="$OPTARG";;
+    f) FILENAME="$OPTARG";;
+    g) FLAG="$OPTARG";;
+    n) REFORMAT_OUTPUT=false;;
+    s) HIDE_PATH=true;;
     *) usage; exit 0;;
   esac
 done
